### ISSUE TITLE
Error when using this plugin

### ISSUE THREAD

**Issue by MattCowBoy** [Chuckland/Sort-Layers-List#1]
Hi,
I tried to use this plugin but when I run it after selecting all layers of an artboard I received this error:

currentPage().deselectAllLayers() is not a function

**Comment by Rojibon** [comment]
I also see an error, when trying to sort layers: 

com.adordzheev.doc.currentPage().deselectAlILayers is not a function. (In
'com.adordzheev.doc.currentPage().deselectAlILayers()', 'com.adordzheev.doc.currentPage().deselectAlILayers' is undefined)
